[package]
name = "fleet-shared"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64 = "0.22.1"
serde = "1.0.202"
unicode_categories = "0.1.1"
z85 = "3.0.5"
