[package]
name = "nix-native-eval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
nixrs = { git = "https://github.com/Anillc/nixrs", version = "0.1.0" }
