[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0-beta.2", features = ["derive", "suggestions", "color"] }
log = "0.4.14"
env_logger = "0.8.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

time = { version = "0.2.25", features = ["serde"] }

lockfile = "0.2.2"
toml = "0.5"
tempfile = "3.2"
once_cell = "1.5"
hostname = "0.3.1"
