[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0.0-beta.2", features = ["derive", "suggestions", "color"] }
log = "0.4.14"
env_logger = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.2", features = ["serde"] }
tempfile = "3.2"
once_cell = "1.5"
hostname = "0.3.1"
age-core = "0.6.0"
peg = "0.7.0"
nixlike = {path = "crates/nixlike"}
age = { version = "0.6.0", features = ["ssh", "armor"] }
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
z85 = "3.0.3"

[workspace]
members = ["crates/nixlike", "cmds/install-secrets"]
