[workspace]
members = ["crates/*", "cmds/*"]
resolver = "2"

[workspace.dependencies]
nixlike = { path = "./crates/nixlike" }
better-command = { path = "./crates/better-command" }
bifrostlink = "0.1.0"
uuid = { version = "1.3.3", features = ["v4"] }
tokio = { version = "1.33.0", features = ["fs", "rt", "macros", "sync", "time", "rt-multi-thread"] }
