[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
clap = { version = "3.0.0-beta.2", features = ["derive", "suggestions", "color"] }
log = "0.4.11"
env_logger = "0.8.1"

serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"

time = { version = "0.2.22", features = ["serde"] }

lockfile = "0.2.2"
toml = "0.5"
tempfile = "3.1.0"
