[package]
name = "terraform-provider-fleet"
edition = "2021"
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1.81"
serde = { workspace = true, features = ["derive"] }
tf-provider = "0.2.2"
tokio.workspace = true
