[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.2.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2021"

[dependencies]
nixlike.workspace = true
better-command.workspace = true
tokio.workspace = true
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["serde"] }
tempfile = "3.10"
once_cell = "1.19"
hostname = "0.3"
age-core = "0.10"
peg = "0.8"
age = { version = "0.10", features = ["ssh", "armor"] }
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
z85 = "3.0"
clap = { version = "4.5", features = ["derive", "env", "wrap_help", "unicode"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tokio-util = { version = "0.7", features = ["codec"] }
async-trait = "0.1"
futures = "0.3"
itertools = "0.12"
shlex = "1.3"
tabled = { version = "0.15" }
owo-colors = { version = "4.0", features = [
	"supports-color",
	"supports-colors",
] }
r2d2 = "0.8.10"
abort-on-drop = "0.2"
unindent = "0.2"
regex = "1.10"
openssh = "0.10"

tracing-indicatif = { version = "0.3", optional = true }
human-repr = { version = "1.1", optional = true }
indicatif = { version = "0.17", optional = true }

[features]
# Not quite stable
indicatif = ["tracing-indicatif", "dep:indicatif", "human-repr", "better-command/indicatif"]
