[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.30", features = ["serde"] }
tempfile = "3.8"
once_cell = "1.18.0"
hostname = "0.3.1"
age-core = "0.9.0"
peg = "0.8.2"
nixlike = { path = "../../crates/nixlike" }
age = { version = "0.9.2", features = ["ssh", "armor"] }
base64 = "0.21.5"
chrono = { version = "0.4.31", features = ["serde"] }
z85 = "3.0.5"
clap = { version = "4.4.7", features = [
	"derive",
	"env",
	"wrap_help",
	"unicode",
] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
async-trait = "0.1.74"
futures = "0.3.29"
tracing-indicatif = "0.3.5"
indicatif = "0.17.7"
itertools = "0.11.0"
shlex = "1.2.0"
tabled = { version = "0.14.0", features = ["color"] }
owo-colors = { version = "3.5.0", features = ["supports-color", "supports-colors"] }
r2d2 = "0.8.10"
abort-on-drop = "0.2.2"
unindent = "0.2.3"
regex = "1.10.2"
openssh = "0.10.1"
human-repr = "1.1.0"
