[package]
name = "fleet"
description = "NixOS configuration management"
version = "0.1.0"
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.2", features = ["serde"] }
tempfile = "3.2"
once_cell = "1.5"
hostname = "0.3.1"
age-core = "0.8.0"
peg = "0.8.0"
nixlike = { path = "../../crates/nixlike" }
age = { version = "0.8.1", features = ["ssh", "armor"] }
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
z85 = "3.0.3"
clap = { version = "3.1.0", features = [
	"derive",
	"env",
	"wrap_help",
	"unicode",
] }
tokio = { version = "1.14.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.3", features = ["fmt", "env-filter"] }
tokio-util = { version = "0.7.0", features = ["codec"] }
async-trait = "0.1.52"
futures = "0.3.17"
