[package]
name = "fleet-install-secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
age = { version = "0.9.0", features = ["ssh"] }
anyhow = "1.0.44"
env_logger = "0.10.0"
log = "0.4.14"
nix = "0.26.1"
serde = "1.0.130"
serde_json = "1.0.89"
clap = { version = "4.0.29", features = [
	"derive",
	"env",
	"wrap_help",
	"unicode",
] }
tempfile = "3.2.0"
z85 = "3.0.3"
