[package]
name = "install-secrets"
version = "0.1.0"
edition = "2018"

[dependencies]
age = { version = "0.6.0", features = ["ssh"] }
anyhow = "1.0.44"
ascii85 = "0.2.1"
env_logger = "0.9.0"
log = "0.4.14"
nix = "0.22.1"
serde = "1.0.130"
serde_json = "1.0.68"
structopt = "0.3.23"
tempfile = "3.2.0"
z85 = "3.0.3"
