[package]
name = "fleet-install-secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
age = { version = "0.8.1", features = ["ssh"] }
anyhow = "1.0.44"
env_logger = "0.9.0"
log = "0.4.14"
nix = "0.25.0"
serde = "1.0.130"
serde_json = "1.0.68"
clap = { version = "3.1.0", features = [
	"derive",
	"env",
	"wrap_help",
	"unicode",
] }
tempfile = "3.2.0"
z85 = "3.0.3"
