[package]
name = "nixlike"
version = "0.1.0"
edition = "2021"

[dependencies]
alejandra = "1.5.0"
rnix = "=0.10.2"
linked-hash-map = "0.5.4"
peg = "0.8.0"
serde = "1.0.130"
thiserror = "1.0.29"
serde_json = "1.0.91"
ron = "0.8.0"
serde-transcode = "1.1.1"
