[package]
name = "nixlike"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
dprint-core = "0.46.2"
peg = "0.7.0"
serde = "1.0.130"
serde_json = "1.0.68"
thiserror = "1.0.29"
