= Remowt agent

Working with remote machine programmatically is not always easy.

Sure, you have ssh, sftp, and that kind of fancy stuff, but what about minimal distributions, routers?

Well, sftp can be replaced with FISH... But what if remote machine isn't accessible over ssh at all? What if the only communication channel you have is uart?

What if remote host has not enough tools to implement the functionality you need?

Remowt is intended to solve this in a way similar to how some RAT toolkits (I.e metasploit) do - you inject minimal agent, setup some communication channel to it (stdio perhaps?), and then you deploy payloads on it, and the payloads perform the actual work.

== Non-targets

Minimal executable size:: As long as it transferred only once, it shouldn't be a problem to keep it a reasonable size.
Be stealthy:: As it solves the problem almost the same way as metasploit, it is possible to use it as something bad, but this is not the remowt intended purpose, and never will be.
